FROM nginx:1.16.0-alpine
RUN rm /etc/nginx/conf.d/default.conf
COPY ./eagle_eye.conf /etc/nginx/conf.d
COPY ./uwsgi_params /etc/nginx/conf.d
EXPOSE 80:80
EXPOSE 443:443
CMD ["nginx", "-g", "daemon off;"]